"use client"

import { useState } from "react"
import { ArrowUpRight, Brain, ChevronDown, CircleCheck, Compass, Copy, GitBranch, Layers, Menu, Shield, Sparkles, TimerReset, X } from "lucide-react"

const moments = [
  ["01", "Notice", "A source arrives", "One evidence card, not a noisy feed."],
  ["02", "Understand", "The system finds context", "Memory and references are visible before a recommendation."],
  ["03", "Choose", "The operator keeps the decision", "A clear approval boundary prevents accidental overreach."],
  ["04", "Record", "The next person can follow it", "A trace captures the why, not just a timestamp."],
]

const agents = [
  ["Atlas", "Research and synthesis", "Reviewing 3 sources", "bg-[#e8f3bd] text-[#283412]"],
  ["Maya", "Planning and handoffs", "Awaiting approval", "bg-[#c8dcff] text-[#172b4d]"],
  ["Scout", "Signal monitoring", "Watching quietly", "bg-[#ffd2bd] text-[#4a2112]"],
]

export default function Page() {
  const [open, setOpen] = useState(false)
  const [chapter, setChapter] = useState(0)
  const [copied, setCopied] = useState(false)
  return <main className="min-h-screen bg-[#f5f2ec] text-[#19201d]">
    <div className="mx-auto min-h-screen max-w-[1500px] border-x border-[#19201d]/10 bg-[#fbfaf7]">
      <header className="sticky top-0 z-20 flex items-center justify-between border-b border-[#19201d]/10 bg-[#fbfaf7]/90 px-5 py-4 backdrop-blur md:px-9"><div className="flex items-center gap-3"><button className="md:hidden" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open ? <X/> : <Menu/>}</button><div className="grid h-9 w-9 place-items-center rounded-full bg-[#19201d] text-[#e8f3bd]"><Sparkles size={17}/></div><div><p className="font-semibold tracking-[-.04em]">Nexus Foundry</p><p className="text-[10px] uppercase tracking-[.18em] text-[#62706a]">Operator edition / v3</p></div></div><div className="hidden items-center gap-7 text-sm text-[#53615b] md:flex"><a href="#story">How it works</a><a href="#agents">Agent cast</a><a href="#proof">Decision proof</a></div><button className="rounded-full bg-[#19201d] px-4 py-2 text-sm font-medium text-[#f5f2ec]">Open a review</button></header>
      {open && <nav className="border-b border-[#19201d]/10 bg-[#f0eee7] p-5 text-sm md:hidden"><div className="grid gap-3"><a href="#story" onClick={()=>setOpen(false)}>How it works</a><a href="#agents" onClick={()=>setOpen(false)}>Agent cast</a><a href="#proof" onClick={()=>setOpen(false)}>Decision proof</a></div></nav>}
      <section className="grid gap-9 px-5 pb-12 pt-12 md:grid-cols-[1.15fr_.85fr] md:px-9 md:pb-20 md:pt-20"><div><p className="mb-5 flex items-center gap-2 text-xs uppercase tracking-[.18em] text-[#62706a]"><span className="h-2 w-2 rounded-full bg-[#7e9c45]"/> Interface-only review fixture</p><h1 className="max-w-3xl text-5xl font-semibold leading-[.93] tracking-[-.075em] md:text-7xl">An agent runtime that keeps its reasoning in view.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#53615b]">This direction turns the dashboard into an operator briefing: calm enough to scan, specific enough to make a call, and honest about what still needs a human.</p><div className="mt-9 flex flex-wrap gap-3"><button className="rounded-full bg-[#d8ea98] px-5 py-3 font-medium text-[#24300e]">Start from the brief <ArrowUpRight className="ml-1 inline" size={16}/></button><button className="rounded-full border border-[#19201d]/15 px-5 py-3 font-medium">See the operating model</button></div></div><div className="relative min-h-[370px] overflow-hidden rounded-[2.5rem] bg-[#19201d] p-6 text-[#f5f2ec] shadow-[12px_14px_0_#d8ea98]"><div className="absolute -right-12 -top-12 h-48 w-48 rounded-full bg-[#d8ea98]/20 blur-2xl"/><div className="relative flex items-start justify-between"><span className="rounded-full border border-white/15 px-3 py-1 text-xs">Today&apos;s operating brief</span><Compass className="text-[#d8ea98]"/></div><div className="relative mt-16"><p className="text-sm text-[#c1c9c4]">The thing to decide</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.05em]">Should the venue shortlist move to outreach?</h2><p className="mt-4 text-sm leading-6 text-[#c1c9c4]">Atlas found three viable options. Maya has prepared a draft. Nothing has been sent.</p></div><div className="relative mt-8 flex items-center justify-between border-t border-white/10 pt-5 text-sm"><span className="flex items-center gap-2"><TimerReset size={16} className="text-[#d8ea98]"/> Updated 11 min ago</span><button className="rounded-full bg-white px-4 py-2 font-medium text-[#19201d]">Review</button></div></div></section>
      <section id="story" className="border-y border-[#19201d]/10 bg-[#f0eee7] px-5 py-12 md:px-9 md:py-16"><div className="mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs uppercase tracking-[.18em] text-[#62706a]">The operating story</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.05em]">One screen, four calm moments.</h2></div><p className="max-w-sm text-sm leading-6 text-[#62706a]">A different design grammar from a dense command center: this is a guided work narrative, not a wall of telemetry.</p></div><div className="grid gap-3 md:grid-cols-4">{moments.map(([number,label,title,description], i)=><button onClick={()=>setChapter(i)} key={number} className={`rounded-3xl border p-5 text-left transition ${chapter===i?"border-[#19201d] bg-[#19201d] text-[#f5f2ec]":"border-[#19201d]/10 bg-[#fbfaf7] hover:border-[#19201d]/40"}`}><div className="flex justify-between"><span className="font-mono text-xs">{number}</span><ChevronDown size={16} className={chapter===i?"rotate-180 transition":"transition"}/></div><p className={`mt-9 text-xs uppercase tracking-[.16em] ${chapter===i?"text-[#d8ea98]":"text-[#62706a]"}`}>{label}</p><h3 className="mt-2 text-xl font-semibold tracking-[-.04em]">{title}</h3><p className={`mt-3 text-sm leading-6 ${chapter===i?"text-[#d6ddd8]":"text-[#62706a]"}`}>{description}</p></button>)}</div></section>
      <section id="agents" className="px-5 py-12 md:px-9 md:py-16"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs uppercase tracking-[.18em] text-[#62706a]">Agent cast</p><h2 className="mt-3 text-4xl font-semibold leading-[.95] tracking-[-.06em]">Each helper has a job. None of them gets to pretend they are the operator.</h2><div className="mt-8 flex items-center gap-3 text-sm text-[#53615b]"><Shield size={18}/><span>Every external step stays behind an approval boundary.</span></div></div><div className="grid gap-3">{agents.map(([name,role,status,tint])=><article key={name} className="grid grid-cols-[auto_1fr_auto] items-center gap-4 rounded-3xl border border-[#19201d]/10 p-5"><div className={`grid h-12 w-12 place-items-center rounded-2xl ${tint}`}><Brain size={21}/></div><div><h3 className="font-semibold">{name}</h3><p className="text-sm text-[#62706a]">{role}</p></div><span className="text-right text-xs text-[#62706a]">{status}</span></article>)}</div></div></section>
      <section id="proof" className="mx-5 mb-5 rounded-[2.5rem] bg-[#d8ea98] p-7 md:mx-9 md:mb-9 md:p-12"><div className="grid items-end gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><p className="text-xs uppercase tracking-[.18em] text-[#587031]">Decision proof</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold leading-[.95] tracking-[-.065em]">A recommendation needs its evidence, its limits, and a readable next move.</h2><div className="mt-8 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-[#19201d] px-4 py-2 text-[#f5f2ec]"><CircleCheck className="mr-1 inline" size={15}/> 3 sources reviewed</span><span className="rounded-full border border-[#19201d]/20 px-4 py-2"><GitBranch className="mr-1 inline" size={15}/> Trace preserved</span><span className="rounded-full border border-[#19201d]/20 px-4 py-2"><Layers className="mr-1 inline" size={15}/> No action executed</span></div></div><div className="rounded-3xl bg-[#fbfaf7] p-6"><p className="text-sm font-medium">Review packet</p><p className="mt-2 text-sm leading-6 text-[#62706a]">A staged bundle of evidence, a draft, and a clear operator decision. This UI demo contains deterministic dummy data only.</p><button onClick={()=>{navigator.clipboard?.writeText("Nexus Foundry V3 review fixture: interface-only, no runtime action."); setCopied(true)}} className="mt-6 w-full rounded-2xl bg-[#19201d] py-3 text-sm font-medium text-[#f5f2ec]"><Copy className="mr-2 inline" size={15}/>{copied ? "Copied review note" : "Copy review note"}</button></div></div></section>
    </div>
  </main>
}
